[package]
name = "leptos-fluent-ssr-hydrate-axum-example"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
axum = { version = "0.7", optional = true }
console_error_panic_hook = "0.1"
tower = { version = "0.4", optional = true }
tower-http = { version = "0.5", features = ["fs"], optional = true }
http = "1"
thiserror = "1"
tokio = { version = "1", features = ["rt-multi-thread"], optional = true }
leptos = "0.6"
leptos_meta = "0.6"
leptos_axum = { version = "0.6", optional = true }
leptos_router = "0.6"
leptos-fluent = { path = "../../leptos-fluent", features = ["yaml"], default-features = false}
fluent-templates = "0.9"
wasm-bindgen = "=0.2.92"

[features]
csr = [
  "leptos/csr",
  "leptos_meta/csr",
  "leptos_router/csr",
]
hydrate = [
  "leptos/hydrate",
  "leptos_meta/hydrate",
  "leptos_router/hydrate",
  "leptos-fluent/hydrate",
]
ssr = [
  "dep:axum",
  "dep:tokio",
  "dep:leptos_axum",
  "dep:tower",
  "dep:tower-http",
  "leptos/ssr",
  "leptos_meta/ssr",
  "leptos_router/ssr",
  "leptos-fluent/ssr",
  "leptos-fluent/axum",
]

[package.metadata.leptos]
# Additional files your application could depends on.
# A change to any file in those directories will trigger a rebuild.
watch-additional-files = ["examples/ssr-hydrate-axum/locales"]
# The name used by wasm-bindgen/cargo-leptos for the JS/WASM bundle. Defaults to the crate name
output-name = "ssr-axum"
# The site root folder is where cargo-leptos generate all output. WARNING: all content of this folder will be erased on a rebuild. Use it in your server setup.
site-root = "target/site-axum"
# The site-root relative folder where all compiled output (JS, WASM and CSS) is written
# Defaults to pkg
site-pkg-dir = "pkg"
# The IP and port (ex: 127.0.0.1:3000) where the server serves the content. Use it in your server setup.
site-addr = "127.0.0.1:3000"
# The port to use for automatic reload monitoring
reload-port = 3001
# The features to use when compiling the bin target
#
# Optional. Can be over-ridden with the command line parameter --bin-features
bin-features = ["ssr"]
# The features to use when compiling the lib target
#
# Optional. Can be over-ridden with the command line parameter --lib-features
lib-features = ["hydrate"]
# The profile to use for the lib target when compiling for release
#
# Optional. Defaults to "release".
lib-profile-release = "wasm-release"

[package.metadata.cargo-all-features]
skip_feature_sets = [
  [],
  ["csr", "ssr"],
  ["csr", "hydrate"],
  ["ssr", "hydrate"],
]
